"use client";

import { FilePdfOutlined } from "@ant-design/icons";
import { App, Button, type ButtonProps } from "antd";
import { useState } from "react";
import { apiDownload } from "@/lib/api-client";
import { errorMessage } from "@/lib/form-errors";
import type { Order } from "@/types/api";

/** Downloads the invoice PDF generated by the API (only paid or refunded orders have an invoice number). */
export function InvoicePdfButton({ order, label = "Download PDF", ...buttonProps }: { order: Pick<Order, "id" | "invoice_no">; label?: string } & Omit<ButtonProps, "onClick" | "loading">) {
  const { message } = App.useApp();
  const [downloading, setDownloading] = useState(false);

  if (!order.invoice_no) {
    return null;
  }

  async function download() {
    setDownloading(true);

    try {
      await apiDownload(`portal/orders/${order.id}/invoice.pdf`, { fileName: `${order.invoice_no}.pdf` });
    } catch (error) {
      message.error(errorMessage(error));
    } finally {
      setDownloading(false);
    }
  }

  return (
    <Button icon={<FilePdfOutlined />} loading={downloading} onClick={() => void download()} {...buttonProps}>
      {label}
    </Button>
  );
}
